### ISSUE TITLE
Request setting SOCKS/HTTP proxy

### ISSUE THREAD

**Issue by DRSDavidSoft** [bitbeans/SimpleDnsCrypt#359]
### Feature Request

Could you please add an option to let DNSCrypt use SOCKS and HTTP proxies? [This](https://github.com/jedisct1/dnscrypt-proxy/blob/7accd726a1871b854aa5d13c60130d85d0ffad26/dnscrypt-proxy/example-dnscrypt-proxy.toml#L92) is the relevant `.toml` configuration line.

### Examples
```toml
# using SOCKS proxy
proxy = "socks5://127.0.0.1:9050"

# using HTTP proxy
proxy = "http://127.0.0.1:3128"
```
